FROM tlkprodregistry.azurecr.io/tlk-airbyte/source-workable:0.1.0.2

COPY airbyte-integrations/connectors/source-workable/source_workable ./source_workable

LABEL io.airbyte.version=0.29.0.11
LABEL io.airbyte.name=airbyte/source-workable